version: '2.4'
services:
  plugin-spellchecker:
    image: docker.io/isoxya/isoxya-plugin-spellchecker:stable
    init: true
    networks:
      processor:
        aliases:
          - isoxya-plugin-spellchecker.localhost
    restart: on-failure
networks:
  processor: {}
