version: "2.4"
services:
  plugin_spellchecker:
    image: ghcr.io/isoxya/isoxya-plugin-spellchecker:testing
    init: true
    networks:
      processor:
        aliases:
          - isoxya-plugin-spellchecker.localhost
    restart: on-failure
networks:
  processor: {}
